// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXdwooKtgEyj_BwIMPN2X4wPwlgzykkWs',
    appId: '1:227025902580:web:f6276e1a2c6a21755d37a1',
    messagingSenderId: '227025902580',
    projectId: 'blood-donation-app-eb901',
    authDomain: 'blood-donation-app-eb901.firebaseapp.com',
    storageBucket: 'blood-donation-app-eb901.firebasestorage.app',
    measurementId: 'G-Z87Q45SX7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXBr5SllSBGZPkC9i1ByV-FTlawUmboKY',
    appId: '1:227025902580:android:80571cbcb5dd0f395d37a1',
    messagingSenderId: '227025902580',
    projectId: 'blood-donation-app-eb901',
    storageBucket: 'blood-donation-app-eb901.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw7-M25jmW9vZlgUd35Eh-2VzzLrjXZ1o',
    appId: '1:227025902580:ios:fb4922e9db82ed5c5d37a1',
    messagingSenderId: '227025902580',
    projectId: 'blood-donation-app-eb901',
    storageBucket: 'blood-donation-app-eb901.firebasestorage.app',
    iosBundleId: 'com.example.fireExtinguisherManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw7-M25jmW9vZlgUd35Eh-2VzzLrjXZ1o',
    appId: '1:227025902580:ios:fb4922e9db82ed5c5d37a1',
    messagingSenderId: '227025902580',
    projectId: 'blood-donation-app-eb901',
    storageBucket: 'blood-donation-app-eb901.firebasestorage.app',
    iosBundleId: 'com.example.fireExtinguisherManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXdwooKtgEyj_BwIMPN2X4wPwlgzykkWs',
    appId: '1:227025902580:web:988a36e9fe41ea475d37a1',
    messagingSenderId: '227025902580',
    projectId: 'blood-donation-app-eb901',
    authDomain: 'blood-donation-app-eb901.firebaseapp.com',
    storageBucket: 'blood-donation-app-eb901.firebasestorage.app',
    measurementId: 'G-PL7MEMKZGL',
  );
}
